aleotex/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::post('/contact','HomeController@postContact');

//Authentication
Route::get('/login', 'UserController@getLogin');
Route::post('/login', 'UserController@postLogin');
Route::get('/logout', 'UserController@getLogout');

//user
Route::resource('user', 'UserController');

//category
Route::resource('category', 'CategoryController');

//material
Route::get('/material/editmode','MaterialController@editMode');
Route::resource('material', 'MaterialController');

//client
Route::resource('client', 'ClientController');

//client
Route::resource('product', 'ItemController');

aleotex/app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table='client';
	protected $primaryKey='client_id';
	protected $fillable = ['client_name', 'picture'];
}

aleotex/app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Input;
use App\Client;
use File;

class ClientController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => [
            'index',
        ]]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return view('client.index')->with('clients',$clients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
        'client_name' => 'required|unique:client',
        'file'   => 'required|mimes:jpeg,bmp,png,jpg',
        ]);


        $input = $request->all();

        $file = Input::file('file');
		
		$client = new Client;
		
		$client->save();
		
        $filename = $client->client_id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_client';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;

		$client->client_name = $input['client_name'];
		$client->picture = $input['picture'];
		$client->save();
        flash()->success('Client successfully created!');
        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('client.edit')->with('client',$client);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
        'client_name' => 'required|unique:client,client_name,'.$id.',client_id',
        'file'          => 'mimes:jpeg,bmp,png,jpg',
        ]);

        $input = $request->all();

        if ($request->hasFile('file'))
		{

        $file = Input::file('file');

        $filename = $id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_client';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;
        }

        $client = Client::findOrFail($id);
        $client->fill($input)->save();
        flash()->success('Client successfully updated!');
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::findOrFail($id);
        File::delete(public_path().'/img_client/'.$client->picture);
        $client->delete();
        flash()->success('Client successfully deleted!');
        return redirect()->route('client.index');
    }
}

aleotex/resources/views/client/create.blade.php
<div class="container" style="padding-bottom: 50px">
<form class="form-horizontal" role="form" method="POST" action="{{ route('client.store') }}" enctype="multipart/form-data">
{!! csrf_field() !!}

    <label class="col-md-4 control-label">Client Name :</label>

            <input type="text" class="form-control" name="client_name" value="{{ old('client_name') }}" style="width:40%">

            @if ($errors->has('client_name'))
                <span>
                    <strong>{{ $errors->first('client_name') }}</strong>
                </span>
            @endif
			
	<label class="col-md-4 control-label">Image :</label>
	<input type="file" name="file">
	<br>
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif

    <button type="submit" class="btn btn-primary">Create Client</button>
</form>
</div>

aleotex/resources/views/client/edit.blade.php
@extends('layouts.app')

@section('title')
Our Clients
@endsection

@section('content')
<section class="our-gallery" id="gallery" style="margin-bottom:100px">	
	<h3 class="text-center" style="padding-bottom: 15px">EDIT ITEM</h3>
	
			<form class="form-horizontal" method="POST" action="{{ route('client.destroy',$client->client_id) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')" value="Delete This Client">
    </form>
	<p class="text-center">Client Image :<br><img src=" {{ URL::asset('img_client') }}/{{ $client->picture }}" width="200px"/></p>
	
<form class="form-horizontal" role="form" method="POST" action="{{ route('client.update',$client->client_id) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <label class="col-md-4 control-label">Client Name :</label>

            <input type="text" class="form-control" name="client_name" value="{{ old('client_name', $client->client_name) }}" style="width:40%">

            @if ($errors->has('client_name'))
                <span>
                    <strong>{{ $errors->first('client_name') }}</strong>
                </span>
            @endif

    <label class="col-md-4 control-label">Image File :</label>
    <input type="file" name="file" value="{{ old('picture', $client->picture) }}">
   
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif

    <button type="submit" class="btn btn-primary">Update Client</button>
	<a href="{{ route('client.index') }}"><button type="button" class="btn btn-success">Go Back</button></a>
</form>
</section>
@endsection

aleotex/resources/views/client/index.blade.php
@extends('layouts.app')

@section('title')
Our Clients
@endsection

@section('content')
<!-- Banner -->	
<section id="home" name="home"></section>
<div id="headerwrap" style="height: 250px">	
	<div class="container">
		<div class="logo">
			<img src="{{ URL::asset('images/logo.png') }}"  style="width: 200px"  />
		</div>
		<div class="banner-info" style="padding: 0">
			<h1>ALFATEX</h1>
			<h3>textile | convection | garment</h3>
	    </div>
	</div> <!--/ .container -->
</div><!--/ #headerwrap -->
<!-- /Banner -->

@if(Auth::check())
				
				<!-- ACCORDION -->
							<div class="accordion ac" id="accordion2" align="center">
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo"><u><b>Add</b> Client</u></a>
									</div>
									<div id="collapseTwo" class="accordion-body collapse">
										<div class="accordion-inner">
											 @include('client.create')
							</div><!-- /accordion-inner -->
						</div><!-- /collapse -->
						@include('flash::message')
					</div><!-- /accordion-group -->
		        </div><!-- Accordion -->
@endif
				

<!-- Gallery -->
<section class="our-team" id="team" style="background-color: #fff; background-image: url('')">
<h3 class="text-center">We Proud to Served Them</h3>
<p class="text-center" style="color:#000">Our main goal is to keep our clients satisfied.</p>
	<div class="container">
		@foreach ($clients as $client)
		<div class="col-sm-4" align="center">
		<a href="{{ URL::asset('img_client') }}/{{ $client->picture }}" title="{{ ucfirst($client->client_name) }}"><img src="{{ URL::asset('img_client') }}/{{ $client->picture }}" alt="{{ ucfirst($client->client_name) }}" class="img-responsive" width="220px"></img></a>
		@if(Auth::check())
		<p style="padding:0; color: #000"><a href="{{route('client.edit',$client->client_id)}}" title="Edit"><img src="{{URL::asset('images')}}/edit.png" width="17px"/></a>
		@endif
		</div>
		@endforeach 
    </div>	
</section>
@endsection