aleotex/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::post('/contact','HomeController@postContact');

//Authentication
Route::get('/login', 'UserController@getLogin');
Route::post('/login', 'UserController@postLogin');
Route::get('/logout', 'UserController@getLogout');

//user
Route::resource('user', 'UserController');

//category
Route::resource('category', 'CategoryController');

//material
Route::get('/material/editmode','MaterialController@editMode');
Route::resource('material', 'MaterialController');

//client
Route::resource('client', 'ClientController');

//client
Route::resource('product', 'ItemController');

aleotex/app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table='item';
	protected $primaryKey='item_id';
	protected $fillable = ['item_name','category_id','picture'];

	public function category()
    {
        return $this->belongsTo('App\Category','category_id','category_id');
    }
}

aleotex/app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Input;
use App\Item;
use App\Category;
use File;


class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => [
            'index',
        ]]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('item.index')->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('item.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
        'item_name' => 'required|unique:item',
		'category_id'	=> 'required',
        'file'  => 'required|mimes:jpeg,bmp,png,jpg',
        ]);

        $input = $request->all();

        if($input['category_id']=="new")
        {
            $this->validate($request, [
            'category_name' => 'required|unique:category',
            ]);

        }

        $file = Input::file('file');
		
		if($input['category_id']=="new")
        {
            $category = new Category;
            $category->category_name = $input['category_name'];
            $category->save();
            $input['category_id'] = $category->category_id;

        }
		
		$item = new Item;
		
		$item->category_id = $input['category_id'];
		
		$item->save();
		
        $filename = $item->item_id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_item';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;

        $item->fill($input)->save();
        flash()->success('Item successfully created!');
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $item = Item::findOrFail($id);
        $data = array('categories'=>$categories,'item'=>$item);
        return view('item.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
        'item_name' => 'required|unique:item,item_name,'.$id.',item_id',
		'category_id'	=> 'required',
        'file'  => 'mimes:jpeg,bmp,png,jpg',
        ]);

        $input = $request->all();
        if ($request->hasFile('file')) {

        $file = Input::file('file');

        $filename = $id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_item';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;
        }

        $item = Item::findOrFail($id);
        $item->fill($input)->save();

        flash()->success('Item successfully updated!');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::findOrFail($id);
        File::delete(public_path().'/img_item/'.$item->picture);
        $item->delete();
        flash()->success('Item successfully deleted!');
        return redirect()->route('product.index');
    }
}

aleotex/resources/views/item/create.blade.php
<div class="container" style="padding-bottom: 50px">
<form class="form-horizontal" role="form" method="POST" action="{{ route('product.store') }}" enctype="multipart/form-data">
{!! csrf_field() !!}

    <label class="col-md-4 control-label">Item Name :</label>

            <input type="text" class="form-control" name="item_name" value="{{ old('item_name') }}" style="width:40%">

            @if ($errors->has('item_name'))
                <span>
                    <strong>{{ $errors->first('item_name') }}</strong>
                </span>
            @endif

    <label class="col-md-4 control-label">Category :</label>

            <select id="category_id" name="category_id" class="form-control" style="width:40%">
					<option value="new">-- New Category..</option>
                @foreach($categories as $category)
                    <option value="{{ $category->category_id }}">{{ $category->category_name }}</option>
                @endforeach
            </select>
			
			<label id="labelcat" class="col-md-4 control-label" style="display:none">New Category Name :</label>
			<input id="category_name" name="category_name" type="text" class="form-control" style="display:none; width:40%" placeholder="Input your new category name here.."/>
			
            @if ($errors->has('category_id'))
                <span>
                    <strong>{{ $errors->first('category_id') }}</strong>
                </span>
            @endif

	<div class="form-group">
	<input type="file" name="file">
	</div>
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif

    <button type="submit" class="btn btn-primary">Create Material</button>
</form>
</div>

@push('scripts')
<script type="text/javascript">
document.getElementById("category_id").selectedIndex = -1;
$('#category_id').change(function() {
    var val=$('#category_id').val();
    if(val=="new") {
        $('#category_name').show();
		$('#labelcat').show();
		}  else  {
      $('#category_name').hide();
      $('#labelcat').hide();
    }
});
</script>
@endpush

aleotex/resources/views/item/edit.blade.php
@extends('layouts.app')

@section('title')
Our Products
@endsection

@section('content')
<section class="our-gallery" id="gallery" style="margin-bottom:100px">	
	<h3 class="text-center" style="padding-bottom: 15px">EDIT ITEM</h3>
	
		<form class="form-horizontal" method="POST" action="{{ route('product.destroy',$item->item_id) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')" value="Delete This Item">
    </form>
	<p class="text-center">Item Image :<br><img src="{{ URL::asset('img_item') }}/{{ $item->picture }}" width="200px"/></p>
	
	
	
<form class="form-horizontal" role="form" method="POST" action="{{ route('product.update',$item->item_id) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <label class="col-md-4 control-label">Item Name :</label>

            <input type="text" class="form-control" name="item_name" value="{{ old('item_name',$item->item_name) }}" style="width:38%">

            @if ($errors->has('item_name'))
                <span>
                    <strong>{{ $errors->first('item_name') }}</strong>
                </span>
            @endif

    <label class="col-md-4 control-label">Category :</label>

            <select name="category_id" class="form-control" style="width:38%">
                @foreach($categories as $category)
                    <option value="{{ $category->category_id }}">{{ $category->category_name }}</option>
                @endforeach
            </select>

            @if ($errors->has('category_id'))
                <span>
                    <strong>{{ $errors->first('category_id') }}</strong>
                </span>
            @endif

	<label class="col-md-4 control-label">Item Image :</label>
	<input type="file" name="file">
	
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif

    <button type="submit" class="btn btn-primary">Update Item</button>
	<a href="{{ route('product.index') }}"><button type="button" class="btn btn-success">Go Back</button></a>
</form>
</section>
@endsection

aleotex/resources/views/item/index.blade.php
@extends('layouts.app')

@section('title')
Our Products
@endsection

@section('content')
<!-- Banner -->	
<section id="home" name="home"></section>
<div id="headerwrap" style="height: 250px">	
	<div class="container">
		<div class="logo">
			<img src="{{ URL::asset('images/logo.png') }}"  style="width: 200px"  />
		</div>
		<div class="banner-info" style="padding: 0">
			<h1>ALFATEX</h1>
			<h3>textile | convection | garment</h3>
	    </div>
	</div> <!--/ .container -->
</div><!--/ #headerwrap -->
<!-- /Banner -->

@if(Auth::check())
				
				<!-- ACCORDION -->
							<div class="accordion ac" id="accordion2" align="center">
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo"><u><b>Add</b> Item</u></a>
									</div>
									<div id="collapseTwo" class="accordion-body collapse">
										<div class="accordion-inner">
											 @include('item.create')
							</div><!-- /accordion-inner -->
						</div><!-- /collapse -->
						@include('flash::message')
					</div><!-- /accordion-group -->
		        </div><!-- Accordion -->
@endif
				
<!-- LOOPING 1 -->
@foreach($categories as $category)
<div id="intro" style="padding: 25px 0; background-color: #585858;">
<h3 class="text-center" style="padding: 0">
@if(Auth::check())
		 <a href="{{route('category.edit',$category->category_id)}}" title="Edit"><img src="{{URL::asset('images')}}/edit.png" width="17px"/></a> - 
@endif
{{ $category->category_name }}</h3>
</div>
<!-- Gallery -->
<section class="our-team" id="team" style="background-color: #fff; background-image: url('')">
	<div class="container">
		@foreach ($category->items as $item)
		<div class="col-sm-3" align="center">
		<a href="{{ URL::asset('img_item') }}/{{ $item->picture }}" title="{{ ucfirst($item->item_name) }}"><img src="{{ URL::asset('img_item') }}/{{ $item->picture }}" alt="{{ ucfirst($item->item_name) }}" class="img-responsive" style="height:220px"></img></a>
		@if(Auth::check())
		<p style="padding:0; padding-bottom: 20px; color: #000"><a href="{{route('product.edit',$item->item_id)}}" title="Edit"><img src="{{URL::asset('images')}}/edit.png" width="17px"/></a>
		@endif
			<b>{{ $item->item_name }}</b></p>
		</div>
		@endforeach 
    </div>	
</section>
<!-- /Gallery -->
@endforeach	
<!-- /LOOPING 1 -->
@endsection