aleotex/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::post('/contact','HomeController@postContact');

//Authentication
Route::get('/login', 'UserController@getLogin');
Route::post('/login', 'UserController@postLogin');
Route::get('/logout', 'UserController@getLogout');

//user
Route::resource('user', 'UserController');

//category
Route::resource('category', 'CategoryController');

//material
Route::get('/material/editmode','MaterialController@editMode');
Route::resource('material', 'MaterialController');

//client
Route::resource('client', 'ClientController');

//client
Route::resource('product', 'ItemController');

aleotex/app/Material.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Material extends Model
{
    protected $table='material';
	protected $primaryKey='material_id';
	protected $fillable = ['material_name', 'picture'];
}

aleotex/app/Http/Controllers/MaterialController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Material;
use Input;
use Storage;
use File;

class MaterialController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => [
            'index',
        ]]);
    }

    public function editMode()
    {
        $materials = Material::all();
        return view('material.editmode')->with('materials',$materials);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $materials = Material::all();
        return view('material.index')->with('materials',$materials);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('material.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
        'material_name' => 'required|unique:material',
        'file'          => 'required|mimes:jpeg,bmp,png,jpg',
        ]);

        $input = $request->all();

        $file = Input::file('file');
		
		$material = new Material;
		
		$material->save();

        $filename = $material->material_id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_material';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;

        $material->fill($input)->save();
        flash()->success('Material successfully created!');
        return redirect()->route('material.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $material = Material::findOrFail($id);
        return view('material.edit')->with('material',$material);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
        'material_name' => 'required|unique:material,material_name,'.$id.',material_id',
        'file'          => 'mimes:jpeg,bmp,png,jpg',
        ]);

        $input = $request->all();

        if ($request->hasFile('file')) {

        $file = Input::file('file');

        $filename = $id.'.'.$file->getClientOriginalExtension();

        $destinationPath =public_path().'/img_material';

        $upload_success = $file->move($destinationPath, $filename);

        $input['picture'] = $filename;
        }

        $material = Material::findOrFail($id);
        $material->fill($input)->save();
        flash()->success('Material successfully updated!');
        return redirect()->route('material.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $material = Material::findOrFail($id);
        File::delete(public_path().'/img_material/'.$material->picture);
        $material->delete();
        flash()->success('Material successfully deleted!');
        return redirect()->route('material.index');
    }

}

aleotex/resources/views/material/create.blade.php
<div class="container" style="padding-bottom: 50px">
<form class="form-horizontal" role="form" method="POST" action="{{ route('material.store') }}" enctype="multipart/form-data">
{!! csrf_field() !!}

    <label class="col-md-4 control-label">Material Name :</label>

            <input type="text" class="form-control" name="material_name" value="{{ old('material_name') }}" style="width:40%">

            @if ($errors->has('material_name'))
                <span>
                    <strong>{{ $errors->first('material_name') }}</strong>
                </span>
            @endif
	
	<label class="col-md-4 control-label">Image :</label>
	<input type="file" name="file">
	<br>
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif

    <button type="submit" class="btn btn-primary">Create Material</button>
</form>
</div>

aleotex/resources/views/material/edit.blade.php
@extends('layouts.app')

@section('title')
Raw Materials
@endsection

@section('content')
<section class="our-gallery" id="gallery" style="margin-bottom:100px">	
	<h3 class="text-center" style="padding-bottom: 15px">EDIT MATERIAL</h3>
	
		<form class="form-horizontal" method="POST" action="{{ route('material.destroy',$material->material_id) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')" value="Delete This Material">
    </form>
	<p class="text-center">Material Image :<br><img src="{{ URL::asset('img_material') }}/{{ $material->picture }}" width="200px"/></p>
	
<form class="form-horizontal" role="form" method="POST" action="{{ route('material.update',$material->material_id) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <label class="col-md-4 control-label">Material Name : </label>

            <input type="text" class="form-control" name="material_name" value="{{ old('material_name', $material->material_name) }}" style="width:38%">

            @if ($errors->has('material_name'))
                <span>
                    <strong>{{ $errors->first('material_name') }}</strong>
                </span>
            @endif

    <label class="col-md-4 control-label">Image File : </label>
    <input type="file" name="file" value="{{ old('picture', $material->picture) }}">
	
            @if ($errors->has('file'))
                <span>
                    <strong>{{ $errors->first('file') }}</strong>
                </span>
            @endif
	<button type="submit" class="btn btn-primary">Update Material</button>
	<a href="{{ route('material.index') }}#gallery"><button type="button" class="btn btn-success">Go Back</button></a>
</form>
</section>
@endsection

aleotex/resources/views/material/index.blade.php
@extends('layouts.app')

@section('title')
Raw Materials
@endsection

@section('content')
<!-- Banner -->	
<section id="home" name="home"></section>
<div id="headerwrap" style="height: 250px">	
	<div class="container">
		<div class="logo">
			<img src="{{ URL::asset('images/logo.png') }}"  style="width: 200px"  />
		</div>
		<div class="banner-info" style="padding: 0">
			<h1>ALFATEX</h1>
			<h3>textile | convection | garment</h3>
	    </div>
	</div> <!--/ .container -->
</div><!--/ #headerwrap -->
<!-- /Banner -->

@if(Auth::check())
				
				<!-- ACCORDION -->
							<div class="accordion ac" id="accordion2" align="center">
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo"><u><b>Add</b> Material</u></a>
									</div>
									<div id="collapseTwo" class="accordion-body collapse">
										<div class="accordion-inner">
											 @include('material.create')
							</div><!-- /accordion-inner -->
						</div><!-- /collapse -->
						@include('flash::message')
					</div><!-- /accordion-group -->
		        </div><!-- Accordion -->
				@endif
				
<!-- Gallery -->
<section class="our-gallery" id="gallery">	
	<h3 class="text-center">RAW MATERIALS</h3>
	<p class="text-center">WE PROUD TO USE LOCAL MATERIALS</p>

	<div class="container">
		<ul class="ch-grid">
			@foreach ($materials as $material)
			<li>
				<div class="ch-item" style="background-image: url('img_material/{{ $material->picture }}'); background-size: 100%">
					<div class="ch-info">
						<h4>{{ ucfirst($material->material_name) }}</h4>
						@if(Auth::check())
						<ul class="social-icons1">
							<li><a href="{{route('material.edit',$material->material_id)}}"><i class="fa fa-edit"></i>Edit</a></li>
						</ul>
						@endif
					</div>
				</div>
			</li>
			@endforeach
		</ul>				
	</div>	
</section>		
<!-- /Gallery -->	
@endsection